server:
  port: 9088
spring:
  application:
    name: usersservice
  data:
    mongodb:
      uri: mongodb+srv://nhn1305:wWp5hlhH1gLDXF2g@cluster0.anu1frm.mongodb.net/test
      database: ms
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: clipnhac123@gmail.com
    password: btcnjvlejbfhjude

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
    oauth2:
      client:
        registration:
          google:
            clientId: 985071277306-62m9upeof9skrtu115fbii56g7p8qtb6.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:9088/oauth2/callback/google"
            scope:
              - email
              - profile
